### ISSUE TITLE
I keep getting error 

### ISSUE THREAD

**Issue by BlessedUzama** [akasakaid/tomarketod#9]
I keep getting this error whenever I run the bot.py file

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tomarketod/bot.py", line 342, in <module>
    app.main()
  File "/data/data/com.termux/files/home/tomarketod/bot.py", line 335, in main
    _min = min(list_countdown) - _tot
           ^^^^^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence

**Comment by akasakaid** [comment]
Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.

**Comment by BlessedUzama** [comment]
> Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.

I was using the bot before without any issues and now it won't work, I tried to get new user token but I couldn't because the bot won't allow me

**Comment by akasakaid** [comment]
> > Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.
> 
> I was using the bot before without any issues and now it won't work, I tried to get new user token but I couldn't because the bot won't allow me

This script no need token, just query. You can try to get new query for your account !

**Comment by BlessedUzama** [comment]
> > > Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.
> > 
> > 
> > I was using the bot before without any issues and now it won't work, I tried to get new user token but I couldn't because the bot won't allow me
> 
> This script no need token, just query. You can try to get new query for your account !

Yeah that what I meant, I can't get new query for my accounts.

**Comment by akasakaid** [comment]
> > > > Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.
> > > 
> > > 
> > > I was using the bot before without any issues and now it won't work, I tried to get new user token but I couldn't because the bot won't allow me
> > 
> > 
> > This script no need token, just query. You can try to get new query for your account !
> 
> Yeah that what I meant, I can't get new query for my accounts.

Really? you can try to get query with android telegram app.

**Comment by BlessedUzama** [comment]
> > > > > Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.
> > > > 
> > > > 
> > > > I was using the bot before without any issues and now it won't work, I tried to get new user token but I couldn't because the bot won't allow me
> > > 
> > > 
> > > This script no need token, just query. You can try to get new query for your account !
> > 
> > 
> > Yeah that what I meant, I can't get new query for my accounts.
> 
> Really? you can try to get query with android telegram app.

Could you tell me how??? Because I couldn't find a video on YouTube on how to get query id with android

**Comment by akasakaid** [comment]
> > > > > > Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.
> > > > > 
> > > > > 
> > > > > I was using the bot before without any issues and now it won't work, I tried to get new user token but I couldn't because the bot won't allow me
> > > > 
> > > > 
> > > > This script no need token, just query. You can try to get new query for your account !
> > > 
> > > 
> > > Yeah that what I meant, I can't get new query for my accounts.
> > 
> > 
> > Really? you can try to get query with android telegram app.
> 
> Could you tell me how??? Because I couldn't find a video on YouTube on how to get query id with android

You can check in readme , im already create a video tutorial for it, you can jump to minute 3/4 in video

**Comment by BlessedUzama** [comment]
> > > > > > > Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.
> > > > > > 
> > > > > > 
> > > > > > I was using the bot before without any issues and now it won't work, I tried to get new user token but I couldn't because the bot won't allow me
> > > > > 
> > > > > 
> > > > > This script no need token, just query. You can try to get new query for your account !
> > > > 
> > > > 
> > > > Yeah that what I meant, I can't get new query for my accounts.
> > > 
> > > 
> > > Really? you can try to get query with android telegram app.
> > 
> > 
> > Could you tell me how??? Because I couldn't find a video on YouTube on how to get query id with android
> 
> You can check in readme , im already create a video tutorial for it, you can jump to minute 3/4 in video

Okay let me check

**Comment by BlessedUzama** [comment]
> > > > > > > Are you already read the readme ? i already explain about how to use it, maybe have mistake in setup the bot.
> > > > > > 
> > > > > > 
> > > > > > I was using the bot before without any issues and now it won't work, I tried to get new user token but I couldn't because the bot won't allow me
> > > > > 
> > > > > 
> > > > > This script no need token, just query. You can try to get new query for your account !
> > > > 
> > > > 
> > > > Yeah that what I meant, I can't get new query for my accounts.
> > > 
> > > 
> > > Really? you can try to get query with android telegram app.
> > 
> > 
> > Could you tell me how??? Because I couldn't find a video on YouTube on how to get query id with android
> 
> You can check in readme , im already create a video tutorial for it, you can jump to minute 3/4 in video

Thanks I was able to get a new query id
